apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: cp-integration-ibm-existing-cluster
spec:
  modules:
    - name: ocp-login
    - name: openshift-cicd
    - name: argocd-bootstrap
    - name: gitops-console-link-job
    - name: gitops-namespace
      variables:
        - name: name
          alias: tools
          value: tools
    - name: gitops-cp-mq
    - name: gitops-cp-ace
    - name: gitops-cp-apic
    - name: gitops-cp-eventstreams
