#!/usr/bin/env bash

oc new-app postgresql-persistent -n "${NAMESPACE}" \
 -p POSTGRESQL_USER="${POSTGRESQL_USER}" \
 -p POSTGRESQL_PASSWORD="${POSTGRESQL_PASSWORD}" \
 -p POSTGRESQL_DATABASE="${POSTGRESQL_DATABASE}" \
 -p VOLUME_CAPACITY="${VOLUME_CAPACITY}"
